site_name: My Knowledge Base
site_url: https://your-domain.com
repo_url: https://github.com/yourusername/your-repo
repo_name: github.com/yourusername/your-repo

# Theme
theme:
  name: material
  features:
    # folders expandable/collapsible
    - navigation.tracking   # highlight current section
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - footnotes
  - meta
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

# Extra
extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

# Analytics
# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto

# Copyright
copyright: Copyright &copy; 2025 shadil A M Name

# Extra
extra:
  version:
    provider: mike
  manifest: manifest.webmanifest
  generator: false
  favicon: assets/favicon.ico
  logo: assets/logo.png
